<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Domain\Ledger\LedgerEntryType;
use App\Domain\Money\Money;
use App\Domain\Payouts\PayoutItemStatus;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Recomputes every balance from first principles and reports disagreement.
 *
 * The snapshot in `instructor_balances` is a cache. This command is its receipt.
 * Each column has an INDEPENDENT source of truth, which is the reason the snapshot
 * is trustworthy at all:
 *
 *   earned    = SUM(ledger_entries) over earning + reversal + clawback + adjustment
 *   paid      = -SUM(ledger_entries) over payout
 *   reserved  = SUM(payout_items) still holding a reservation (submitted, unknown)
 *   available = generated by MySQL from the three above, so it cannot drift at all
 *
 * Plus one structural check: every allocation must satisfy
 * platform + Σ lines == gross. That is the invariant the entire design rests on, so
 * it is verified against stored data rather than only in unit tests.
 *
 * In production this belongs on a schedule wired to paging. Silent snapshot drift is
 * the failure mode most likely to go unnoticed, because everything keeps working —
 * it just stops being true.
 */
final class VerifyLedger extends Command
{
    protected $signature = 'ledger:verify
        {--instructor= : Verify a single instructor.}
        {--fix : Rewrite drifting snapshots from the ledger. The ledger always wins.}';

    protected $description = 'Recompute instructor balances from the ledger and report any drift.';

    public function handle(): int
    {
        $problems = 0;

        $problems += $this->verifyBalances();
        $problems += $this->verifyAllocations();

        if ($problems === 0) {
            $this->components->info('Ledger verified. Snapshots agree with the ledger and every allocation balances.');

            return self::SUCCESS;
        }

        $this->components->error("{$problems} problem(s) found.");

        return self::FAILURE;
    }

    private function verifyBalances(): int
    {
        $earnedTypes = [
            LedgerEntryType::Earning->value,
            LedgerEntryType::Reversal->value,
            LedgerEntryType::Clawback->value,
            LedgerEntryType::Adjustment->value,
        ];

        $query = DB::table('instructor_balances as b')
            ->select('b.instructor_id', 'b.currency', 'b.earned_minor', 'b.paid_minor', 'b.reserved_minor')
            ->selectSub(
                DB::table('ledger_entries')
                    ->selectRaw('COALESCE(SUM(amount_minor), 0)')
                    ->whereColumn('instructor_id', 'b.instructor_id')
                    ->whereIn('type', $earnedTypes),
                'ledger_earned',
            )
            ->selectSub(
                DB::table('ledger_entries')
                    ->selectRaw('COALESCE(-SUM(amount_minor), 0)')
                    ->whereColumn('instructor_id', 'b.instructor_id')
                    ->where('type', LedgerEntryType::Payout->value),
                'ledger_paid',
            )
            ->selectSub(
                DB::table('payout_items')
                    ->selectRaw('COALESCE(SUM(amount_minor), 0)')
                    ->whereColumn('instructor_id', 'b.instructor_id')
                    ->whereIn('status', [
                        PayoutItemStatus::Submitted->value,
                        PayoutItemStatus::Unknown->value,
                    ]),
                'items_reserved',
            )
            ->orderBy('b.instructor_id');

        if ($this->option('instructor') !== null) {
            $query->where('b.instructor_id', (int) $this->option('instructor'));
        }

        $drifting = [];
        $checked = 0;

        foreach ($query->cursor() as $row) {
            $checked++;

            $deltas = [
                'earned' => (int) $row->earned_minor - (int) $row->ledger_earned,
                'paid' => (int) $row->paid_minor - (int) $row->ledger_paid,
                'reserved' => (int) $row->reserved_minor - (int) $row->items_reserved,
            ];

            if ($deltas === ['earned' => 0, 'paid' => 0, 'reserved' => 0]) {
                continue;
            }

            $drifting[] = [
                $row->instructor_id,
                Money::of((int) $row->earned_minor, $row->currency)->format().' vs '
                    .Money::of((int) $row->ledger_earned, $row->currency)->format(),
                Money::of((int) $row->paid_minor, $row->currency)->format().' vs '
                    .Money::of((int) $row->ledger_paid, $row->currency)->format(),
                Money::of((int) $row->reserved_minor, $row->currency)->format().' vs '
                    .Money::of((int) $row->items_reserved, $row->currency)->format(),
            ];

            if ($this->option('fix')) {
                DB::table('instructor_balances')
                    ->where('instructor_id', $row->instructor_id)
                    ->update([
                        'earned_minor' => (int) $row->ledger_earned,
                        'paid_minor' => (int) $row->ledger_paid,
                        'reserved_minor' => (int) $row->items_reserved,
                        'version' => DB::raw('version + 1'),
                        'updated_at' => now(),
                    ]);
            }
        }

        $this->components->twoColumnDetail('Balances checked', (string) $checked);

        if ($drifting === []) {
            return 0;
        }

        $this->components->error('Snapshot drift detected (snapshot vs recomputed):');
        $this->table(['Instructor', 'Earned', 'Paid', 'Reserved'], $drifting);

        if ($this->option('fix')) {
            $this->components->warn(count($drifting).' snapshot(s) rewritten from the ledger.');

            return 0;
        }

        $this->line('  Re-run with --fix to rewrite them from the ledger.');

        return count($drifting);
    }

    /**
     * The money invariant, checked against stored data.
     *
     * platform + Σ lines must equal gross for every allocation. A single row failing
     * this means money was created or destroyed, which is the one thing that must
     * never be tolerated.
     */
    private function verifyAllocations(): int
    {
        $unbalanced = DB::table('allocations as a')
            ->leftJoin('allocation_lines as l', 'l.allocation_id', '=', 'a.id')
            ->groupBy('a.id', 'a.gross_minor', 'a.platform_minor', 'a.instructor_pool_minor', 'a.accrual_period')
            ->havingRaw('a.platform_minor + COALESCE(SUM(l.amount_minor), 0) <> a.gross_minor')
            ->orHavingRaw('COALESCE(SUM(l.amount_minor), 0) <> a.instructor_pool_minor')
            ->select(
                'a.id',
                'a.accrual_period',
                'a.gross_minor',
                'a.platform_minor',
                'a.instructor_pool_minor',
            )
            ->selectRaw('COALESCE(SUM(l.amount_minor), 0) as line_total')
            ->limit(50)
            ->get();

        $total = DB::table('allocations')->count();
        $this->components->twoColumnDetail('Allocations checked', (string) $total);

        if ($unbalanced->isEmpty()) {
            return 0;
        }

        $this->components->error('Allocations that do not balance:');
        $this->table(
            ['Allocation', 'Period', 'Gross', 'Platform', 'Pool', 'Σ lines'],
            $unbalanced->map(fn ($r): array => [
                $r->id, $r->accrual_period, $r->gross_minor,
                $r->platform_minor, $r->instructor_pool_minor, $r->line_total,
            ])->all(),
        );

        return $unbalanced->count();
    }
}
