<?php

declare(strict_types=1);

use App\Domain\Payouts\PayoutItemStatus;
use App\Filament\Resources\InstructorBalanceResource;
use App\Filament\Resources\InstructorBalanceResource\Pages\ListInstructorBalances;
use App\Filament\Resources\InstructorBalanceResource\Pages\ViewInstructorBalance;
use App\Filament\Resources\InstructorBalanceResource\RelationManagers\PayoutItemsRelationManager;
use App\Models\Instructor;
use App\Models\InstructorBalance;
use App\Models\PayoutBatch;
use App\Models\PayoutItem;
use App\Models\User;
use Livewire\Livewire;

beforeEach(function () {
    $this->actingAs(User::factory()->create());
});

it('lists instructors with money outstanding', function () {
    $owed = Instructor::factory()->create(['name' => 'Owed Instructor']);
    InstructorBalance::factory()->for($owed)->owed(120_000)->create();

    $settled = Instructor::factory()->create(['name' => 'Settled Instructor']);
    InstructorBalance::factory()->for($settled)->create();

    Livewire::test(ListInstructorBalances::class)
        ->assertSuccessful()
        // The default filter is "owed money", because that is the question an
        // operator actually opens this screen to answer.
        ->assertCanSeeTableRecords(InstructorBalance::where('instructor_id', $owed->id)->get())
        ->assertCanNotSeeTableRecords(InstructorBalance::where('instructor_id', $settled->id)->get());
});

it('shows amounts as formatted money, never raw minor units', function () {
    $instructor = Instructor::factory()->create();
    InstructorBalance::factory()->for($instructor)->owed(120_000)->create();

    Livewire::test(ListInstructorBalances::class)
        ->assertSuccessful()
        // 120_000 piastres must read as 1,200.00 EGP. A screen that leaks minor units
        // is how someone reads a balance as a hundred times too small.
        ->assertSee('1,200.00 EGP')
        ->assertDontSee('120000');
});

it('separates in-flight money from outstanding money', function () {
    // The distinction the whole design rests on, and the one an operator most needs
    // to see during an incident: reserved money is neither paid nor payable.
    $instructor = Instructor::factory()->create();

    InstructorBalance::factory()->for($instructor)->create([
        'earned_minor' => 100_000,
        'paid_minor' => 0,
        'reserved_minor' => 100_000,
    ]);

    Livewire::test(ListInstructorBalances::class)
        ->filterTable('population', 'in_flight')
        ->assertSuccessful()
        ->assertCanSeeTableRecords(InstructorBalance::all())
        ->assertSee('1,000.00 EGP');
});

it('surfaces a negative balance from a clawback', function () {
    $instructor = Instructor::factory()->create();

    InstructorBalance::factory()->for($instructor)->create([
        'earned_minor' => 0,
        'paid_minor' => 50_000,
    ]);

    Livewire::test(ListInstructorBalances::class)
        ->filterTable('population', 'negative')
        ->assertSuccessful()
        ->assertCanSeeTableRecords(InstructorBalance::all())
        ->assertSee('-500.00 EGP');
});

it('flags balances held back by the payout minimum', function () {
    $dusty = Instructor::factory()->create();
    InstructorBalance::factory()->for($dusty)->owed(5_000)->create();

    $payable = Instructor::factory()->create();
    InstructorBalance::factory()->for($payable)->owed(120_000)->create();

    Livewire::test(ListInstructorBalances::class)
        ->filterTable('population', 'below_minimum')
        ->assertSuccessful()
        ->assertCanSeeTableRecords(InstructorBalance::where('instructor_id', $dusty->id)->get())
        ->assertCanNotSeeTableRecords(InstructorBalance::where('instructor_id', $payable->id)->get());
});

it('shows one instructor\'s position on the view page', function () {
    $instructor = Instructor::factory()->create();

    InstructorBalance::factory()->for($instructor)->create([
        'earned_minor' => 200_000,
        'paid_minor' => 50_000,
        'reserved_minor' => 30_000,
    ]);

    Livewire::test(ViewInstructorBalance::class, ['record' => $instructor->id])
        ->assertSuccessful()
        ->assertSee('2,000.00 EGP')   // earned
        ->assertSee('500.00 EGP')     // paid
        ->assertSee('300.00 EGP')     // in flight
        ->assertSee('1,200.00 EGP');  // outstanding, generated by MySQL
});

it('lists payout history including uncertain outcomes', function () {
    $instructor = Instructor::factory()->create();
    $balance = InstructorBalance::factory()->for($instructor)->owed(200_000)->create();
    $batch = PayoutBatch::factory()->forPeriod('2026-01')->create();

    $unknown = PayoutItem::factory()->create([
        'payout_batch_id' => $batch->id,
        'instructor_id' => $instructor->id,
        'amount_minor' => 80_000,
        'status' => PayoutItemStatus::Unknown,
    ]);

    Livewire::test(PayoutItemsRelationManager::class, [
        'ownerRecord' => $balance,
        'pageClass' => ViewInstructorBalance::class,
    ])
        ->assertSuccessful()
        ->assertCanSeeTableRecords([$unknown])
        // Spelled out, not shown as a failure. An operator who reads 'unknown' as
        // 'failed' is one click away from paying twice.
        ->assertSee('Unknown — asking provider')
        ->assertDontSee('Failed — released');
});

// ─────────────────────────────────────────────────────────────────────────────
// Read-only is a design constraint, not a shortcut
// ─────────────────────────────────────────────────────────────────────────────

it('offers no way to write to the money core from the admin panel', function () {
    $instructor = Instructor::factory()->create();
    $balance = InstructorBalance::factory()->for($instructor)->owed(120_000)->create();

    // An editable balance would be a write path that bypasses the ledger entirely —
    // the one thing the design forbids. Corrections belong in an `adjustment` ledger
    // entry with a recorded reason, never in a form field.
    expect(InstructorBalanceResource::canCreate())->toBeFalse()
        ->and(InstructorBalanceResource::canEdit($balance))->toBeFalse()
        ->and(InstructorBalanceResource::canDelete($balance))->toBeFalse();

    Livewire::test(PayoutItemsRelationManager::class, [
        'ownerRecord' => $balance,
        'pageClass' => ViewInstructorBalance::class,
    ])->assertSuccessful();

    expect((new PayoutItemsRelationManager)->isReadOnly())->toBeTrue();
});

it('requires authentication', function () {
    auth()->logout();

    $this->get('/admin/instructor-balances')->assertRedirect('/admin/login');
});
