<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('instructor_balances', function (Blueprint $table) {
            // One row per instructor, so the primary key IS the instructor.
            $table->foreignId('instructor_id')->primary()->constrained()->restrictOnDelete();
            $table->char('currency', 3)->default('EGP');

            $table->bigInteger('earned_minor')->default(0);
            $table->bigInteger('paid_minor')->default(0);

            // ───────────────────────────────────────────────────────────────────
            // The column that makes the unreliable provider survivable.
            //
            // While a payout item is 'submitted' or 'unknown', its amount lives
            // here: neither paid nor available. So the next payout run computes
            // available = earned - paid - reserved and CANNOT include money that
            // might already be in flight — without needing to know the outcome of
            // the first attempt yet.
            // ───────────────────────────────────────────────────────────────────
            $table->bigInteger('reserved_minor')->default(0);

            // Generated by MySQL, not by PHP. It is arithmetically impossible for
            // this to drift from its inputs, which removes a whole class of bug.
            $table->bigInteger('available_minor')
                ->storedAs('earned_minor - paid_minor - reserved_minor');

            // Optimistic concurrency counter, bumped on every write.
            $table->unsignedBigInteger('version')->default(0);

            $table->timestamp('updated_at')->nullable();

            // "Who is worth paying this run?" — answered from this index alone,
            // never by scanning the ledger.
            $table->index(['currency', 'available_minor'], 'instructor_balances_payable_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('instructor_balances');
    }
};
