<?php

declare(strict_types=1);

namespace App\Filament\Resources;

use App\Filament\Resources\InstructorBalanceResource\Pages;
use App\Filament\Resources\InstructorBalanceResource\RelationManagers\PayoutItemsRelationManager;
use App\Models\InstructorBalance;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

/**
 * Instructor balances and payout history. Read-only by design.
 *
 * ── Why this reads the snapshot, not the ledger ───────────────────────────────
 *
 * Every column here comes from `instructor_balances`: one row per instructor. The
 * ledger holds tens of millions of rows and exists for audit and rebuild, not for
 * rendering a table. Answering "what is this instructor owed" with SUM() over the
 * ledger would work on a demo dataset and fall over in production.
 *
 * `available_minor` is a MySQL generated column, so the figure on screen cannot
 * disagree with its own inputs, and `ledger:verify` proves the inputs agree with the
 * ledger. That is the chain that makes a cached number trustworthy enough to show.
 *
 * ── Why read-only ────────────────────────────────────────────────────────────
 *
 * Not laziness, and not only because the brief allows it. An editable balance would
 * be a write path into the money core that bypasses the ledger entirely — the one
 * thing the whole design forbids. Corrections belong in an `adjustment` ledger entry
 * with a recorded reason, never in a form field.
 */
final class InstructorBalanceResource extends Resource
{
    protected static ?string $model = InstructorBalance::class;

    protected static ?string $navigationIcon = 'heroicon-o-banknotes';

    protected static ?string $navigationLabel = 'Instructor Balances';

    protected static ?string $modelLabel = 'instructor balance';

    protected static ?string $slug = 'instructor-balances';

    public static function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn (Builder $query) => $query->with('instructor'))
            ->columns([
                Tables\Columns\TextColumn::make('instructor.name')
                    ->label('Instructor')
                    ->searchable()
                    ->sortable()
                    ->description(fn (InstructorBalance $record): string => $record->instructor->email),

                Tables\Columns\TextColumn::make('earned_minor')
                    ->label('Earned')
                    ->formatStateUsing(fn (InstructorBalance $record): string => $record->earned_minor->format())
                    ->sortable()
                    ->alignEnd()
                    ->tooltip('Lifetime recognised earnings, from the ledger.'),

                Tables\Columns\TextColumn::make('paid_minor')
                    ->label('Paid')
                    ->formatStateUsing(fn (InstructorBalance $record): string => $record->paid_minor->format())
                    ->sortable()
                    ->alignEnd()
                    ->color('gray')
                    ->tooltip('Successfully sent through the payment provider.'),

                Tables\Columns\TextColumn::make('reserved_minor')
                    ->label('In flight')
                    ->formatStateUsing(fn (InstructorBalance $record): string => $record->reserved_minor->format())
                    ->sortable()
                    ->alignEnd()
                    ->color(fn (InstructorBalance $record): string => $record->reserved_minor->isPositive() ? 'warning' : 'gray')
                    ->tooltip(
                        'Held by a payout whose outcome is not yet known. Neither paid nor '
                        .'available — this is what stops a second run paying it again.'
                    ),

                Tables\Columns\TextColumn::make('available_minor')
                    ->label('Outstanding')
                    ->formatStateUsing(fn (InstructorBalance $record): string => $record->available_minor->format())
                    ->sortable()
                    ->alignEnd()
                    ->weight('bold')
                    // Negative means a clawback exceeded earnings — netted against
                    // future earnings, never collected by demanding money back.
                    ->color(fn (InstructorBalance $record): string => match (true) {
                        $record->available_minor->isNegative() => 'danger',
                        $record->available_minor->isPositive() => 'success',
                        default => 'gray',
                    })
                    ->tooltip('earned − paid − in flight. Generated by the database, not by the application.'),

                Tables\Columns\TextColumn::make('version')
                    ->label('Writes')
                    ->sortable()
                    ->alignEnd()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->tooltip('Optimistic-concurrency counter. Useful for proving a replay changed nothing.'),

                Tables\Columns\TextColumn::make('updated_at')
                    ->label('Last movement')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(),
            ])
            ->filters([
                // One mutually exclusive selector, not four independent toggles.
                //
                // The first version had a default "owed money" filter alongside
                // separate "negative" and "in flight" toggles — which AND together, so
                // filtering for negative balances while the default was still on
                // returned nothing. These are really four views of the same table, so
                // they belong in one control.
                Tables\Filters\SelectFilter::make('population')
                    ->label('Show')
                    ->options([
                        'outstanding' => 'Owed money',
                        'in_flight' => 'Has a payout in flight',
                        'negative' => 'Negative (clawback)',
                        'below_minimum' => 'Below payout minimum',
                        'all' => 'Everyone',
                    ])
                    ->default('outstanding')
                    ->selectablePlaceholder(false)
                    ->query(function (Builder $query, array $data): Builder {
                        return match ($data['value'] ?? 'outstanding') {
                            'in_flight' => $query->where('reserved_minor', '>', 0),
                            'negative' => $query->where('available_minor', '<', 0),
                            'below_minimum' => $query
                                ->where('available_minor', '>', 0)
                                ->where('available_minor', '<', (int) config('ledger.payout.minimum_minor')),
                            'all' => $query,
                            default => $query->where('available_minor', '>', 0),
                        };
                    }),
            ])
            ->defaultSort('available_minor', 'desc')
            ->recordUrl(fn (InstructorBalance $record): string => Pages\ViewInstructorBalance::getUrl(['record' => $record->instructor_id]))
            // No bulk actions and no row actions: there is deliberately no write path
            // into the money core from the admin panel.
            ->paginated([25, 50, 100]);
    }

    /** @return array<class-string> */
    public static function getRelations(): array
    {
        return [PayoutItemsRelationManager::class];
    }

    /** @return array<string, mixed> */
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListInstructorBalances::route('/'),
            'view' => Pages\ViewInstructorBalance::route('/{record}'),
        ];
    }

    public static function canCreate(): bool
    {
        return false;
    }

    public static function canEdit(mixed $record): bool
    {
        return false;
    }

    public static function canDelete(mixed $record): bool
    {
        return false;
    }
}
