<?php

declare(strict_types=1);

use App\Actions\Allocation\AllocateSubscriptionPeriod;
use App\Actions\Allocation\AllocationOutcome;
use App\Actions\Allocation\AllocationResult;
use App\Domain\Allocation\AllocationStrategyResolver;
use App\Domain\Allocation\WeightedByWatchTime;
use App\Domain\Ledger\LedgerEntryType;
use App\Domain\Ledger\LedgerWriter;
use App\Domain\Subscriptions\Plan;
use App\Models\Allocation;
use App\Models\AllocationLine;
use App\Models\Course;
use App\Models\Engagement;
use App\Models\Instructor;
use App\Models\InstructorBalance;
use App\Models\LedgerEntry;
use App\Models\Payment;
use App\Models\Student;
use App\Models\Subscription;

/**
 * Builds a student on a monthly plan for January 2026, engaged with $count
 * instructors, each watching $seconds.
 *
 * @param  list<int>  $seconds  watch time per instructor, in order
 * @return array{0: Subscription, 1: list<Instructor>}
 */
function scenario(int $instructors = 3, array $seconds = [], string $period = '2026-01'): array
{
    $student = Student::factory()->create();

    $subscription = Subscription::factory()
        ->for($student)
        ->plan(Plan::Monthly)
        ->startingOn('2026-01-01')
        ->create();

    Payment::factory()->forSubscription($subscription)->create();

    $created = [];

    for ($i = 0; $i < $instructors; $i++) {
        $instructor = Instructor::factory()->create();
        $course = Course::factory()->for($instructor)->create();

        Engagement::factory()
            ->for($student)
            ->forCourse($course)
            ->inPeriod($period)
            ->watched($seconds[$i] ?? 3_600)
            ->create();

        $created[] = $instructor;
    }

    return [$subscription, $created];
}

function allocate(Subscription $subscription, string $period = '2026-01'): AllocationResult
{
    return app(AllocateSubscriptionPeriod::class)->execute($subscription, $period);
}

// ─────────────────────────────────────────────────────────────────────────────
// The happy path, end to end
// ─────────────────────────────────────────────────────────────────────────────

it('recognises a full month, takes the platform cut and splits the rest', function () {
    [$subscription, $instructors] = scenario(instructors: 3);

    $result = allocate($subscription);

    expect($result->outcome)->toBe(AllocationOutcome::Allocated);

    $allocation = $result->allocation->fresh('lines');

    // 299.00 EGP for all of January, 30% platform cut.
    expect($allocation->gross_minor->minor)->toBe(29_900)
        ->and($allocation->platform_minor->minor)->toBe(8_970)
        ->and($allocation->instructor_pool_minor->minor)->toBe(20_930)
        ->and($allocation->days_in_period)->toBe(31)
        ->and($allocation->strategy)->toBe('equal_weight');

    // The worked example: 20_930 ÷ 3 → two instructors get the extra piastre.
    $amounts = $allocation->lines->sortBy('instructor_id')
        ->pluck('amount_minor')->map(fn ($m) => $m->minor)->values()->all();

    expect($amounts)->toBe([6_977, 6_977, 6_976])
        ->and(array_sum($amounts))->toBe(20_930);
});

it('keeps gross exactly equal to platform plus instructor lines', function () {
    [$subscription] = scenario(instructors: 3);

    $allocation = allocate($subscription)->allocation->fresh('lines');

    expect($allocation->balances())->toBeTrue();
});

it('writes one earning ledger entry per non-zero line and moves the balance', function () {
    [$subscription, $instructors] = scenario(instructors: 3);

    allocate($subscription);

    expect(LedgerEntry::count())->toBe(3);

    foreach ($instructors as $instructor) {
        $entry = LedgerEntry::where('instructor_id', $instructor->id)->sole();

        expect($entry->type->value)->toBe('earning')
            ->and($entry->source_type)->toBe('allocation_line')
            ->and($entry->amount_minor->minor)->toBeIn([6_976, 6_977])
            // Business time, not wall clock: January earnings occurred in January.
            ->and($entry->occurred_at->format('Y-m'))->toBe('2026-01');

        $balance = InstructorBalance::find($instructor->id);

        expect($balance->earned_minor->minor)->toBe($entry->amount_minor->minor)
            ->and($balance->paid_minor->isZero())->toBeTrue()
            ->and($balance->reserved_minor->isZero())->toBeTrue()
            // Generated by MySQL from the other three columns.
            ->and($balance->available_minor->minor)->toBe($entry->amount_minor->minor);
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Idempotency — the requirement the whole schema is shaped around
// ─────────────────────────────────────────────────────────────────────────────

it('running allocation twice does not pay twice', function () {
    [$subscription, $instructors] = scenario(instructors: 3);

    $first = allocate($subscription);
    $second = allocate($subscription);

    expect($first->outcome)->toBe(AllocationOutcome::Allocated)
        // Reported distinctly, so a replay is never mistaken for real work.
        ->and($second->outcome)->toBe(AllocationOutcome::AlreadyAllocated)
        ->and($second->allocation->id)->toBe($first->allocation->id);

    // Nothing duplicated at any layer.
    expect(Allocation::count())->toBe(1)
        ->and(AllocationLine::count())->toBe(3)
        ->and(LedgerEntry::count())->toBe(3);

    // And critically: balances did not move a second time.
    foreach ($instructors as $instructor) {
        expect(InstructorBalance::find($instructor->id)->earned_minor->minor)
            ->toBeIn([6_976, 6_977]);
    }
});

it('running allocation ten times leaves balances untouched after the first', function () {
    [$subscription, $instructors] = scenario(instructors: 3);

    allocate($subscription);

    // Compare minor units, not Money instances: two Money objects with the same
    // value are equal but not identical, and toBe() checks identity.
    $earnedSnapshot = fn (): array => InstructorBalance::orderBy('instructor_id')
        ->get()
        ->mapWithKeys(fn ($b) => [$b->instructor_id => $b->earned_minor->minor])
        ->all();

    $versionSnapshot = fn (): array => InstructorBalance::orderBy('instructor_id')
        ->pluck('version', 'instructor_id')->all();

    $earnedBefore = $earnedSnapshot();
    $versionsBefore = $versionSnapshot();

    foreach (range(1, 9) as $ignored) {
        expect(allocate($subscription)->outcome)->toBe(AllocationOutcome::AlreadyAllocated);
    }

    expect($earnedSnapshot())->toBe($earnedBefore)
        // The version counter is the stronger assertion: it proves no write
        // happened at all, not merely that the value landed back where it started.
        ->and($versionSnapshot())->toBe($versionsBefore)
        ->and(LedgerEntry::count())->toBe(3);
});

it('the ledger unique index blocks a replay even if the allocation guard is bypassed', function () {
    // Simulating the worst case: something hand-crafts a second ledger write for an
    // allocation line that was already recorded. The index must stop it.
    [$subscription, $instructors] = scenario(instructors: 1);

    allocate($subscription);

    $line = AllocationLine::sole();
    $writer = app(LedgerWriter::class);

    $replayed = DB::transaction(fn () => $writer->append(
        instructorId: $line->instructor_id,
        type: LedgerEntryType::Earning,
        amount: $line->amount_minor,
        sourceType: 'allocation_line',
        sourceId: $line->id,
    ));

    // false, not an exception: a replay is a no-op, not an error.
    expect($replayed)->toBeFalse()
        ->and(LedgerEntry::count())->toBe(1)
        ->and(InstructorBalance::find($line->instructor_id)->earned_minor->minor)
        ->toBe($line->amount_minor->minor);
});

// ─────────────────────────────────────────────────────────────────────────────
// Attribution edges
// ─────────────────────────────────────────────────────────────────────────────

it('gives the whole period to the platform when nobody was engaged', function () {
    $student = Student::factory()->create();
    $subscription = Subscription::factory()->for($student)
        ->plan(Plan::Monthly)->startingOn('2026-01-01')->create();
    Payment::factory()->forSubscription($subscription)->create();

    // No engagement rows at all.
    $allocation = allocate($subscription)->allocation->fresh('lines');

    expect($allocation->platform_minor->minor)->toBe(29_900)
        ->and($allocation->instructor_pool_minor->isZero())->toBeTrue()
        ->and($allocation->lines)->toHaveCount(0)
        ->and(LedgerEntry::count())->toBe(0)
        // Recorded, not skipped: the money is accounted for and the period will not
        // be reprocessed on the next run.
        ->and($allocation->balances())->toBeTrue();
});

it('counts an instructor once even across several watched courses', function () {
    $student = Student::factory()->create();
    $subscription = Subscription::factory()->for($student)
        ->plan(Plan::Monthly)->startingOn('2026-01-01')->create();
    Payment::factory()->forSubscription($subscription)->create();

    $prolific = Instructor::factory()->create();
    $other = Instructor::factory()->create();

    // Three courses by the same instructor. Without aggregation this instructor
    // would take 3/4 of the pool instead of 1/2.
    foreach (range(1, 3) as $ignored) {
        $course = Course::factory()->for($prolific)->create();
        Engagement::factory()->for($student)->forCourse($course)->inPeriod('2026-01')->create();
    }

    $course = Course::factory()->for($other)->create();
    Engagement::factory()->for($student)->forCourse($course)->inPeriod('2026-01')->create();

    $allocation = allocate($subscription)->allocation->fresh('lines');

    expect($allocation->lines)->toHaveCount(2);

    $byInstructor = $allocation->lines->keyBy('instructor_id');

    expect($byInstructor[$prolific->id]->amount_minor->minor)->toBe(10_465)
        ->and($byInstructor[$other->id]->amount_minor->minor)->toBe(10_465);
});

it('honours the watch-time strategy when it is the active one', function () {
    config()->set('ledger.allocation_strategy', WeightedByWatchTime::NAME);
    app()->forgetInstance(AllocationStrategyResolver::class);

    // 6:3:1 over a 20_930 pool.
    [$subscription] = scenario(instructors: 3, seconds: [6_000, 3_000, 1_000]);

    $allocation = allocate($subscription)->allocation->fresh('lines');

    $amounts = $allocation->lines->sortBy('instructor_id')
        ->pluck('amount_minor')->map(fn ($m) => $m->minor)->values()->all();

    expect($allocation->strategy)->toBe('watch_time')
        ->and($amounts)->toBe([12_558, 6_279, 2_093])
        ->and(array_sum($amounts))->toBe(20_930);
});

it('records a zero line without a ledger entry for an unwatched course', function () {
    config()->set('ledger.allocation_strategy', WeightedByWatchTime::NAME);
    app()->forgetInstance(AllocationStrategyResolver::class);

    [$subscription, $instructors] = scenario(instructors: 2, seconds: [3_600, 0]);

    $allocation = allocate($subscription)->allocation->fresh('lines');
    $byInstructor = $allocation->lines->keyBy('instructor_id');

    expect($allocation->lines)->toHaveCount(2)
        ->and($byInstructor[$instructors[1]->id]->amount_minor->isZero())->toBeTrue()
        // The engagement is on record; a zero-value ledger entry would be noise.
        ->and(LedgerEntry::count())->toBe(1);
});

// ─────────────────────────────────────────────────────────────────────────────
// Historical rate snapshotting
// ─────────────────────────────────────────────────────────────────────────────

it('uses the rate snapshotted on the subscription, not today\'s config', function () {
    $student = Student::factory()->create();

    // Sold at a 20% cut.
    $subscription = Subscription::factory()->for($student)
        ->plan(Plan::Monthly)->startingOn('2026-01-01')
        ->platformShareBps(2_000)->create();
    Payment::factory()->forSubscription($subscription)->create();

    $course = Course::factory()->create();
    Engagement::factory()->for($student)->forCourse($course)->inPeriod('2026-01')->create();

    // The platform has since raised its cut to 50%.
    config()->set('ledger.platform_share_bps', 5_000);

    $allocation = allocate($subscription)->allocation->fresh('lines');

    // Still 20%: 29_900 × 20% = 5_980 platform, 23_920 to the instructor.
    expect($allocation->platform_minor->minor)->toBe(5_980)
        ->and($allocation->instructor_pool_minor->minor)->toBe(23_920);
});

// ─────────────────────────────────────────────────────────────────────────────
// Periods outside the term
// ─────────────────────────────────────────────────────────────────────────────

it('skips a period before the term starts', function () {
    [$subscription] = scenario(instructors: 1);

    $result = allocate($subscription, '2025-12');

    expect($result->outcome)->toBe(AllocationOutcome::Skipped)
        ->and($result->reason)->toContain('outside the recognised term')
        ->and(Allocation::count())->toBe(0);
});

it('skips a period after a cancellation', function () {
    $student = Student::factory()->create();

    $subscription = Subscription::factory()->for($student)
        ->plan(Plan::Annual)->startingOn('2026-01-01')
        ->cancelledOn('2026-04-30')->create();
    Payment::factory()->forSubscription($subscription)->create();

    $course = Course::factory()->create();
    Engagement::factory()->for($student)->forCourse($course)->inPeriod('2026-04')->create();
    Engagement::factory()->for($student)->forCourse($course)->inPeriod('2026-05')->create();

    expect(allocate($subscription, '2026-04')->outcome)->toBe(AllocationOutcome::Allocated)
        // The month after they left must recognise nothing — this is what makes a
        // pro-rata refund a no-op against instructor balances.
        ->and(allocate($subscription, '2026-05')->outcome)->toBe(AllocationOutcome::Skipped);
});

it('skips a subscription with no payment received', function () {
    $subscription = Subscription::factory()->plan(Plan::Monthly)->startingOn('2026-01-01')->create();

    $result = allocate($subscription);

    expect($result->outcome)->toBe(AllocationOutcome::Skipped)
        ->and($result->reason)->toContain('no payment');
});
