<?php

declare(strict_types=1);

namespace App\Models;

use App\Casts\MoneyCast;
use App\Domain\Money\Money;
use Database\Factories\InstructorBalanceFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * A denormalised balance, so "what is this instructor owed" never scans the
 * ledger.
 *
 * The ledger is the truth; this is a cache with a receipt. Every column has an
 * independent source it can be verified against:
 *
 *   earned / paid  → SUM over ledger_entries
 *   reserved       → SUM over payout_items still holding a reservation
 *   available      → generated by MySQL from the other three, so it cannot drift
 *
 * `ledger:verify` recomputes all of them and reports disagreement. If they ever
 * differ, the ledger wins.
 *
 * @property int $instructor_id
 * @property string $currency
 * @property Money $earned_minor
 * @property Money $paid_minor
 * @property Money $reserved_minor
 * @property-read Money $available_minor
 * @property int $version
 */
final class InstructorBalance extends Model
{
    /** @use HasFactory<InstructorBalanceFactory> */
    use HasFactory;

    public const CREATED_AT = null;

    protected $primaryKey = 'instructor_id';

    public $incrementing = false;

    protected $fillable = [
        'instructor_id', 'currency',
        'earned_minor', 'paid_minor', 'reserved_minor', 'version',
    ];

    /** Generated column: never written by the application. */
    protected $guarded = ['available_minor'];

    protected function casts(): array
    {
        return [
            'earned_minor' => MoneyCast::class,
            'paid_minor' => MoneyCast::class,
            'reserved_minor' => MoneyCast::class,
            'available_minor' => MoneyCast::class,
            'version' => 'integer',
        ];
    }

    /** @return BelongsTo<Instructor, $this> */
    public function instructor(): BelongsTo
    {
        return $this->belongsTo(Instructor::class);
    }

    /**
     * Payout history for this balance.
     *
     * Declared here as well as on Instructor because this row's primary key IS the
     * instructor id, so the join is direct. It lets the admin screen read a balance
     * and its payout history without hopping through Instructor — one less query on a
     * page whose whole purpose is to avoid touching the ledger.
     *
     * @return HasMany<PayoutItem, $this>
     */
    public function payoutItems(): HasMany
    {
        return $this->hasMany(PayoutItem::class, 'instructor_id', 'instructor_id');
    }

    /** @return HasMany<LedgerEntry, $this> */
    public function ledgerEntries(): HasMany
    {
        return $this->hasMany(LedgerEntry::class, 'instructor_id', 'instructor_id');
    }
}
