<?php

declare(strict_types=1);

namespace App\Filament\Resources\InstructorBalanceResource\Pages;

use App\Filament\Resources\InstructorBalanceResource;
use App\Models\InstructorBalance;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;

final class ViewInstructorBalance extends ViewRecord
{
    protected static string $resource = InstructorBalanceResource::class;

    public function infolist(Infolist $infolist): Infolist
    {
        return $infolist->schema([
            Section::make('Position')
                ->description('earned − paid − in flight = outstanding. The last figure is generated by MySQL.')
                ->columns(4)
                ->schema([
                    TextEntry::make('instructor.name')->label('Instructor')->columnSpan(4),

                    TextEntry::make('earned_minor')
                        ->label('Earned')
                        ->formatStateUsing(fn (InstructorBalance $record): string => $record->earned_minor->format()),

                    TextEntry::make('paid_minor')
                        ->label('Paid')
                        ->formatStateUsing(fn (InstructorBalance $record): string => $record->paid_minor->format()),

                    TextEntry::make('reserved_minor')
                        ->label('In flight')
                        ->formatStateUsing(fn (InstructorBalance $record): string => $record->reserved_minor->format())
                        ->color(fn (InstructorBalance $record): string => $record->reserved_minor->isPositive() ? 'warning' : 'gray')
                        // Only when something is actually held. The first version showed
                        // this under 0.00 too, telling an operator a payout was in an
                        // unknown state when nothing was — the one screen where a false
                        // alarm is most likely to prompt someone to "fix" it by hand.
                        ->helperText(fn (InstructorBalance $record): ?string => $record->reserved_minor->isPositive()
                            ? 'Held by a payout whose outcome is not yet known. Not payable by another run.'
                            : null),

                    TextEntry::make('available_minor')
                        ->label('Outstanding')
                        ->weight('bold')
                        ->formatStateUsing(fn (InstructorBalance $record): string => $record->available_minor->format()),
                ]),
        ]);
    }
}
